DROP TABLE researcher CASCADE;

DROP TYPE callstatus CASCADE;
DROP TABLE call CASCADE;

DROP TYPE appstatus CASCADE;
DROP TABLE proposal CASCADE;

DROP TABLE collaborator CASCADE;

DROP TABLE conflict CASCADE;

DROP TABLE review CASCADE;

DROP TABLE meeting CASCADE;

DROP TYPE parttype CASCADE;
DROP TABLE participant CASCADE;

DROP TABLE discussion CASCADE;
